In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
x = iris.data

In [8]:
# x

In [9]:
 y = iris.target

In [11]:
# y

In [12]:
# class 0 --->[1,0,0]
# class 1 --->[0,1,0]
# class 2 --->[0,0,1]

In [16]:
from keras.utils import to_categorical

In [17]:
y = to_categorical(y)

In [19]:
# y

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.33,random_state=42)

In [27]:
# y_train

In [28]:
from sklearn.preprocessing import MinMaxScaler

In [29]:
prepro = MinMaxScaler()

In [30]:
prepro.fit(X_train)

MinMaxScaler()

In [31]:
scaler_x_train = prepro.transform(X_train)
scaler_x_test = prepro.transform(X_test)

In [34]:
# scaler_x_test

In [35]:
from keras.models import Sequential
from keras.layers import Dense

In [37]:
model = Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [38]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [40]:
model.fit(scaler_x_train,y_train,epochs=150,verbose=2)

Epoch 1/150
4/4 - 0s - loss: 0.4750 - accuracy: 0.9100
Epoch 2/150
4/4 - 0s - loss: 0.4736 - accuracy: 0.9100
Epoch 3/150
4/4 - 0s - loss: 0.4727 - accuracy: 0.9300
Epoch 4/150
4/4 - 0s - loss: 0.4711 - accuracy: 0.9300
Epoch 5/150
4/4 - 0s - loss: 0.4689 - accuracy: 0.9300
Epoch 6/150
4/4 - 0s - loss: 0.4671 - accuracy: 0.9300
Epoch 7/150
4/4 - 0s - loss: 0.4654 - accuracy: 0.9100
Epoch 8/150
4/4 - 0s - loss: 0.4636 - accuracy: 0.9100
Epoch 9/150
4/4 - 0s - loss: 0.4621 - accuracy: 0.8900
Epoch 10/150
4/4 - 0s - loss: 0.4609 - accuracy: 0.8900
Epoch 11/150
4/4 - 0s - loss: 0.4591 - accuracy: 0.8800
Epoch 12/150
4/4 - 0s - loss: 0.4574 - accuracy: 0.8900
Epoch 13/150
4/4 - 0s - loss: 0.4558 - accuracy: 0.8900
Epoch 14/150
4/4 - 0s - loss: 0.4543 - accuracy: 0.8800
Epoch 15/150
4/4 - 0s - loss: 0.4528 - accuracy: 0.8700
Epoch 16/150
4/4 - 0s - loss: 0.4513 - accuracy: 0.8600
Epoch 17/150
4/4 - 0s - loss: 0.4501 - accuracy: 0.8600
Epoch 18/150
4/4 - 0s - loss: 0.4488 - accuracy: 0.8400
E

Epoch 147/150
4/4 - 0s - loss: 0.2101 - accuracy: 0.9500
Epoch 148/150
4/4 - 0s - loss: 0.2094 - accuracy: 0.9700
Epoch 149/150
4/4 - 0s - loss: 0.2090 - accuracy: 0.9600
Epoch 150/150
4/4 - 0s - loss: 0.2083 - accuracy: 0.9600


In [41]:
model.predict_classes(scaler_x_test)

c:\users\asus\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [42]:
predictions = model.predict_classes(scaler_x_test)

c:\users\asus\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [44]:
# y_test

In [46]:
y_test.argmax(axis = 1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [47]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [48]:
print(confusion_matrix(predictions,y_test.argmax(axis=1)))

[[19  0  0]
 [ 0 14  0]
 [ 0  1 16]]


In [49]:
print(classification_report(predictions,y_test.argmax(axis=1)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      1.00      0.97        14
           2       1.00      0.94      0.97        17

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



In [50]:
print(accuracy_score(predictions,y_test.argmax(axis=1)))

0.98


In [51]:
model.save('myfirstmodel.h5')

In [52]:
from keras.models import load_model

In [53]:
model = load_model('myfirstmodel.h5')

In [54]:
model.predict_classes(scaler_x_test)

c:\users\asus\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)